# Path related
raw_dataset_dir: data\dataset\
raw_dataset_path: data\processed\raw_dataset.pkl
cleaned_raw_dataset_path: data\processed\raw_dataset.pkl
train_set_path:
- data/processed/x_train.pkl
- data/processed/y_train.pkl
valid_set_path:
- data/processed/x_valid.pkl
- data/processed/y_valid.pkl
test_set_path:
- data/processed/x_test.pkl
- data/processed/y_test.pkl

train_set_eda:
- data/processed/x_train_eda.pkl
- data/processed/y_train_eda.pkl
valid_set_eda:
- data/processed/x_valid_eda.pkl
- data/processed/y_valid_eda.pkl
test_set_eda:
- data/processed/x_test_eda.pkl
- data/processed/y_test_eda.pkl

train_set_clean:
- data/processed/x_train_clean.pkl
- data/processed/y_train_clean.pkl
valid_set_clean:
- data/processed/x_valid_clean.pkl
- data/processed/y_valid_clean.pkl
test_set_clean:
- data/processed/x_test_clean.pkl
- data/processed/y_test_clean.pkl

train_set_full:
- data/processed/x_train_full.pkl
- data/processed/y_train_full.pkl

standardizer_file:
- data/processed/standardizer.pkl

# -- Preprocessing Related -- #
imputer_num: models/imputer_num.pkl
imputer_cat: models/imputer_cat.pkl
ohe_path: models/ohe_encoder.pkl
le_path: models/le_encoder.pkl
le_label_path : models/le_label.pkl
scaler_path: models/scaler.pkl

# -- Training Log Related -- #
training_log_path: log/training_log.json
production_model_path: models/production_model.pkl

# Debug related
print_debug: true

datetime_columns:
- policy_bind_date
- incident_date

int32_col:
- months_as_customer
- age
- policy_number
- policy_annual_premium
- insured_zip
- capital_gains
- capital_loss
- incident_hour_of_the_day
- total_claim_amount
- injury_claim
- property_claim
- vehicle_claim

object_columns:
- policy_state
- policy_csl
- policy_deductable
- umbrella_limit
- insured_sex
- insured_hobbies
- incident_type
- collision_type
- incident_severity
- authorities_contacted
- incident_state
- incident_city
- number_of_vehicles_involved
- property_damage
- bodily_injuries
- witnesses
- auto_year
- police_report_available
- auto_make
- auto_model
- fraud_reported

int32_predictor:
- months_as_customer
- age
- policy_number
- policy_annual_premium
- insured_zip
- capital_gains
- capital_loss
- incident_hour_of_the_day
- total_claim_amount
- injury_claim
- property_claim
- vehicle_claim

object_predictor:
- policy_deductable
- umbrella_limit
- number_of_vehicles_involved
- bodily_injuries
- witnesses
- auto_year
- policy_state
- policy_csl
- insured_sex
- insured_hobbies
- incident_type
- collision_type
- incident_severity
- authorities_contacted
- incident_state
- incident_city
- property_damage
- police_report_available
- auto_make
- auto_model
#- fraud_reported

label : fraud_reported

predictor:

#- incident_date
- months_as_customer
- age
- policy_number
- policy_annual_premium
- insured_zip
- capital_gains
- capital_loss
- incident_hour_of_the_day
- total_claim_amount
- injury_claim
- property_claim
- vehicle_claim
- policy_deductable
- umbrella_limit
- number_of_vehicles_involved
- bodily_injuries
- witnesses
- auto_year
- policy_state
- policy_csl
- insured_sex
- insured_hobbies
- incident_type
- collision_type
- incident_severity
- authorities_contacted
- incident_state
- incident_city
- property_damage
- police_report_available
- auto_make
- auto_model

api_predictor:
#- policy_bind_date
#- incident_date
- months_as_customer
- age
- policy_number
- policy_annual_premium
- insured_zip
- capital_gains
- capital_loss
- incident_hour_of_the_day
- total_claim_amount
- injury_claim
- property_claim
- vehicle_claim
- policy_deductable
- umbrella_limit
- number_of_vehicles_involved
- bodily_injuries
- witnesses
- auto_year
- policy_state
- policy_csl
- insured_sex
- insured_hobbies
- incident_type
- collision_type
- incident_severity
- authorities_contacted
- incident_state
- incident_city
- property_damage
- police_report_available
- auto_make
- auto_model

model_params_path:
- data/model_params/class_weight.pkl
- data/model_params/decision_tree.pkl
- data/model_params/random_forest.pkl
- data/model_params/adaboost.pkl
- data/model_params/gradient_boosting.pkl
- data/model_params/xgboost.pkl
- data/model_params/xgboost2.pkl

# range of data related
months_as_customer:
- -1
- 500
age:
- 19
- 65
policy_number:
- 100000
- 999999
policy_annual_premium:
- 400
- 2500
insured_zip:
- 430000
- 630000
capital_gains:
- -1
- 150000
capital_loss:
- -120000
- 1
incident_hour_of_the_day:
- -1
- 23
total_claim_amount:
- 99
- 120000
injury_claim:
- -1
- 25000
property_claim:
- -1
- 25000
vehicle_claim:
- 0
- 80000
policy_deductable:
- '500'
- '1000'
- '2000'
umbrella_limit:
- '0'
- '1000000'
- '2000000'
- '3000000'
- '4000000'
- '5000000'
- '6000000'
- '7000000'
- '8000000'
- '9000000'
- '10000000'
- '-1000000'
number_of_vehicles_involved:
- '1'
- '2'
- '3'
- '4'
bodily_injuries:
- '0'
- '1'
- '2'
witnesses:
- '0'
- '1'
- '2'
- '3'
auto_year:
- '1995'
- '1999'
- '2005'
- '2006'
- '2011'
- '2007'
- '2003'
- '2009'
- '2010'
- '2013'
- '2002'
- '2015'
- '1997'
- '2012'
- '2008'
- '2014'
- '2001'
- '2000'
- '1998'
- '2004'
- '1996'
policy_state:
- 'OH'
- 'IL'
- 'IN'
policy_csl:
- '250/500'
- '100/300'
- '500/1000'
insured_sex:
- 'FEMALE'
- 'MALE'
insured_hobbies:
- 'reading'
- 'exercise'
- 'paintball'
- 'bungie-jumping'
- 'movies'
- 'golf'
- 'camping'
- 'kayaking'
- 'yachting'
- 'hiking'
- 'video-games'
- 'skydiving'
- 'base-jumping'
- 'board-games'
- 'polo'
- 'chess'
- 'dancing'
- 'sleeping'
- 'cross-fit'
- 'basketball'
incident_type:
- 'Multi-vehicle Collision'
- 'Single Vehicle Collision'
- 'Vehicle Theft'
- 'Parked Car'
collision_type:
- 'Rear Collision'
- 'Side Collision'
- 'Front Collision'
- 'UNKNOWN'
incident_severity:
- 'Minor Damage'
- 'Total Loss'
- 'Major Damage'
- 'Trivial Damage'
authorities_contacted:
- 'Police'
- 'Fire'
- 'Other'
- 'Ambulance'
- 'nan'
incident_state:
- 'NY'
- 'SC'
- 'WV'
- 'VA'
- 'NC'
- 'PA'
- 'OH'
incident_city:
- 'Springfield'
- 'Arlington'
- 'Columbus'
- 'Northbend'
- 'Hillsdale'
- 'Riverwood'
- 'Northbrook'
property_damage:
- 'UNKNOWN'
- 'NO'
- 'YES'
police_report_available:
- 'UNKNOWN'
- 'NO'
- 'YES'
auto_make:
- 'Saab'
- 'Dodge'
- 'Suburu'
- 'Nissan'
- 'Chevrolet'
- 'Ford'
- 'BMW'
- 'Toyota'
- 'Audi'
- 'Accura'
- 'Volkswagen'
- 'Jeep'
- 'Mercedes'
- 'Honda'
auto_model:
- 'RAM'
- 'Wrangler'
- 'A3'
- 'Neon'
- 'MDX'
- 'Jetta'
- 'Passat'
- 'A5'
- 'Legacy'
- 'Pathfinder'
- 'Malibu'
- '92x'
- 'Camry'
- 'Forrestor'
- 'F150'
- '95'
- 'E400'
- '93'
- 'Grand Cherokee'
- 'Escape'
- 'Tahoe'
- 'Maxima'
- 'Ultima'
- 'X5'
- 'Highlander'
- 'Civic'
- 'Silverado'
- 'Fusion'
- 'ML350'
- 'Impreza'
- 'Corolla'
- 'TL'
- 'CRV'
- 'C300'
- '3 Series'
- 'X6'
- 'M5'
- 'Accord'
- 'RSX'


backend_columns:
  - months_as_customer
  - age
  - policy_number
  - policy_annual_premium
  - insured_zip
  - capital_gains
  - capital_loss
  - incident_hour_of_the_day
  - total_claim_amount
  - injury_claim
  - property_claim
  - vehicle_claim
  - policy_state_IL
  - policy_state_IN
  - policy_state_OH
  - policy_csl_100/300
  - policy_csl_250/500
  - policy_csl_500/1000
  - policy_deductable_1000
  - policy_deductable_2000
  - policy_deductable_500
  - insured_sex_MALE
  - insured_hobbies_base-jumping
  - insured_hobbies_basketball
  - insured_hobbies_board-games
  - insured_hobbies_bungie-jumping
  - insured_hobbies_camping
  - insured_hobbies_chess
  - insured_hobbies_cross-fit
  - insured_hobbies_dancing
  - insured_hobbies_exercise
  - insured_hobbies_golf
  - insured_hobbies_hiking
  - insured_hobbies_kayaking
  - insured_hobbies_movies
  - insured_hobbies_paintball
  - insured_hobbies_polo
  - insured_hobbies_reading
  - insured_hobbies_skydiving
  - insured_hobbies_sleeping
  - insured_hobbies_video-games
  - insured_hobbies_yachting
  - collision_type_Front Collision
  - collision_type_Rear Collision
  - collision_type_Side Collision
  - collision_type_UNKNOWN
  - authorities_contacted_Ambulance
  - authorities_contacted_Fire
  - authorities_contacted_Other
  - authorities_contacted_Police
  - authorities_contacted_nan
  - incident_state_NC
  - incident_state_NY
  - incident_state_OH
  - incident_state_PA
  - incident_state_SC
  - incident_state_VA
  - incident_state_WV
  - incident_city_Arlington
  - incident_city_Columbus
  - incident_city_Hillsdale
  - incident_city_Northbend
  - incident_city_Northbrook
  - incident_city_Riverwood
  - incident_city_Springfield
  - property_damage_NO
  - property_damage_UNKNOWN
  - property_damage_YES
  - police_report_available_NO
  - police_report_available_UNKNOWN
  - police_report_available_YES
  - auto_make_Accura
  - auto_make_Audi
  - auto_make_BMW
  - auto_make_Chevrolet
  - auto_make_Dodge
  - auto_make_Ford
  - auto_make_Honda
  - auto_make_Jeep
  - auto_make_Mercedes
  - auto_make_Nissan
  - auto_make_Saab
  - auto_make_Suburu
  - auto_make_Toyota
  - auto_make_Volkswagen
  - auto_model_3 Series
  - auto_model_92x
  - auto_model_93
  - auto_model_95
  - auto_model_A3
  - auto_model_A5
  - auto_model_Accord
  - auto_model_C300
  - auto_model_CRV
  - auto_model_Camry
  - auto_model_Civic
  - auto_model_Corolla
  - auto_model_E400
  - auto_model_Escape
  - auto_model_F150
  - auto_model_Forrestor
  - auto_model_Fusion
  - auto_model_Grand Cherokee
  - auto_model_Highlander
  - auto_model_Impreza
  - auto_model_Jetta
  - auto_model_Legacy
  - auto_model_M5
  - auto_model_MDX
  - auto_model_ML350
  - auto_model_Malibu
  - auto_model_Maxima
  - auto_model_Neon
  - auto_model_Passat
  - auto_model_Pathfinder
  - auto_model_RAM
  - auto_model_RSX
  - auto_model_Silverado
  - auto_model_TL
  - auto_model_Tahoe
  - auto_model_Ultima
  - auto_model_Wrangler
  - auto_model_X5
  - auto_model_X6
  - incident_type
  - witnesses
  - incident_severity
  - auto_year
  - umbrella_limit
  - bodily_injuries
  - number_of_vehicles_involved


label_categories:
- 'FRAUD'
- 'TIDAK FRAUD'


# EDA
numeric_eda:
- injury_claim
- property_claim
- vehicle_claim

categoric_eda:
- insured_hobbies
- incident_type
- collision_type
- incident_severity
- authorities_contacted
- incident_state
- property_damage

eda_predictor:
- injury_claim
- property_claim
- vehicle_claim
- insured_hobbies
- incident_type
- collision_type
- incident_severity
- authorities_contacted
- incident_state
- property_damage
